project:
  type: website
  output-dir: docs

website:
  title: "Aqui teste"
  navbar:
  search: false
  
      left:
      - text: "Início"
        file: index.qmd
      right:
      - text: "Sobre"
        menu:
        - text: "Texto 1"
        - text: "Texto 2"
        - text: "Texto 3"
      # - icon: github
    #     href: https://github.com/
    #   - icon: twitter
    #     href: https://twitter.com
page-layout: custom
format:
  html:
    # grid: 
    #   sidebar-width: 300px
    #   body-width: 900px
    #   margin-width: 300px
    #   gutter-width: 1.5rem
    #   
    theme: custom.scss
    css: styles.css

editor: visual


